### ISSUE TITLE
[1장] 읽기 연산이 압도적인 시스템에 RDB가 적합한 이유

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#1]

**Comment by HYEMSTER** [comment]
- 읽기 연산이 많으면 데이터를 비정규화해서 NoSQL에 담아두고 쓰는 게 RDB보다 빠르지 않을까?
- RDB에서는 인덱싱을 사용할 수 있어서 RDB가 더 빠른가?
- RW/RO endpoint를 다르게 두어 RO만 스케일링 가능하니까 읽기 쿼리의 병렬 수행이 가능해서 그런가?
- 읽기 성능 측면보다는 연산이 복잡한 쿼리에 유리하기 때문이 아닐까?

-> 그래도 읽기 연산에 RDB가 더 적합하다는 의견에 100% 동감하지 못하겠다.. 더 찾아보기로

**Comment by behappyalltt** [comment]
RDB가 읽기 연산에서 더 좋은 점은
1. 연산이 복잡한 쿼리가 가능하다
2. 인덱싱이 가능하다
3. ACID를 지원하기 때문에 일관성이 유지되어야 하는 경우 유리하다
4. 모니터링, 백업 등이 용이하다

정도 있는 것 같은데
아무리 생각해도, 다시 찾아 봐도 읽기 연산이 압도적으로 많은 경우에는 NoSQL이 더 유리한 것 같다
누가 저자한테 물어보면 좋겠네요

**Comment by ycheese** [comment]
책에서 얘기하는 읽기 연산에 해당하는 기능은 `주변 사업장 검색`과 `사업장 정보 확인`이었음.
이 중 더 많은 비중을 차지하는 건 `주변 사업장 검색`임.

여기에 초점을 두어서 생각해봤는데
**특정한 조건에 맞는 데이터 검색이 필요하기 때문**인 것 같다. (사업장 정보 확인은 사업장 ID만 있으면 검색 가능하니까)
실제로 RDB가 이런 검색을 더 빠르게 지원한다고 한다.
일관성 있는 데이터 제공이 필요하다는 점도 한 몫 하지 않았을까?

읽기 연산이 압도적인 경우에는 NoSQL이 유리하다고 생각하지만 책에서 이렇게 말하는 이유는 이 시스템에서 특별히 유리한 이유가 있기 때문이라고 추측함

**Comment by behappyalltt** [comment]
읽기 연산이 많다는 것보다 특정한 조건에 맞는 데이터 검색이 필요하다는 것에 초점을 두면 그럴 수도 있겠네요
여기에 인덱싱을 걸면 속도가 더 빨라질 것이니 일리가 있습니다
채은님 멋져요~👍🏾

**Comment by HYEMSTER** [comment]
특정 조건에 맞는 데이터 검색에서 RDB가 유리하다는 말이 맞는 것 같네요..😮

그 외에는 사실 아직 잘 이해가 되지는 않는데
스키마 변경이 자주 발생할 수 있는 데이터라면 RDB가 적합할 수 있을 것 같다고도 생각했는데 이 시스템에는 해당하지 않는 내용인 것 같구요
(NoSQL에서는 스키마 변경 시 데이터의 정합성 보장이 어렵기 때문)
사업장 정보는 **최종적 일관성**만 달성하면 된다고 했으니 이 또한 관련 없는 이야기라고 생각했습니다.

채은님 멋져요~👍🏿
