### ISSUE TITLE
[4장] 분산 메세지 큐 모니터링은 어떻게 하는 것이 좋을까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/system-design-interview#12]
1. 응답 시간 측정
1-1. 응답 시간을 측정하여 제대로 작동하고 있는지 확인하면 좋겠다
1-2. 대기 시간도 하면 좋을 듯
2. 로그
2-1. 로그를 쌓아서 에러를 추적하고, 노티를 보내서 담당자에게 전달
3. CPU, 메모리, 네트워크
3-1. 사용량을 모니터링 해서 병목 현상 방지
4. 노드 모니터링은 어떻게 하는 것이 좋을까요?
5. 더 모니터링 해야 할 것들이 있을까요?

**Comment by HYEMSTER** [comment]
손) datadog에게 맡긴다.
주) 로그 모니터링이라는 게 큐 하나하나? 하는건가요?
손) 큐 자체를 모니터링하려면 CPU, Memory로 큐의 상태를 확인하고.... 메세지가 정상적으로 처리되지 못했을 땐 데드레터토픽을 발행한다. (어케 하는 진 잘 몰라요)
