### ISSUE TITLE
[4장] 메시지 지연/예약 전송을 소비자 기준으로 할 수는 없을까?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#13]
책에서 `주문 후 30분 이내 미결제시 주문 취소` 를 예시로 들었는데 이건 소비자 기준으로 확인해야 하는 문제지 않나? 더 깊게 이해하고 싶다.

메시지를 받아서 처리하는 것 -> 소비자의 몫
30 분 이후 미결제한 주문 취소(소비자가 할 일)이 30분+a에 일어나는 데 괜찮은 것인가

**Comment by HYEMSTER** [comment]
소비자 기준으로 한다면 어떻게 되는 건가?
- 소비자가 너무 많은 책임을 가지게 되는 것 아닌가?
- 소비자 기준으로 하면 지연 시간이 사라질까?

- 소비자가 언제 가져갈 지 모르니까??
  - 생산자(message[sendDate=9:55]) -> 임시 저장소(message) -> 소비자(즉시 처리)
