### ISSUE TITLE
[5장] 서버와 DB 사이에 큐를 두는 것

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#15]
177p.
서버 -> DB 데이터 전달 과정에서 데이터의 소실을 막기 위해 중간에 큐를 두었는데, 만약 큐에 장애가 발생한다면 결국 메시지는 소실되고 마는 것 아닐까요?
이런 문제를 만날 때마다 큐의 장애를 대비해 앞에 또 새로운 컴포넌트를 두고... 그 컴포넌트 장애를 대비해 또 또 새로운 컴포넌트를 두고... 이런식으로 무제한으로 추가해야 하는 게 아닌가 생각이 들어서요..

중간에 큐를 두면 문제가 확실히 해결된다!
이런 느낌이 아닌 것 같아서 저를 이해시켜주셨으면 좋겠습니다.

**Comment by ycheese** [comment]
카프카 자체의 에러는 카프카가 해결해야 한다.
메시지 큐를 만드는 것이 초점이 아니라서 그런 의미에서 책이 이야기한 것 같다.
외부 서비스를 사용할 것이니까 에러가 나지 않는다고 가정

단시간에 엄청난 요청으로 카프카의 처리가 밀리는 것도 카프카가 처리한다?
**-> 카프카를 믿자**
