### ISSUE TITLE
[5장] 데이터를 집계하는 시점에서 3가지 방안을 제시하는데 보통은 이 3가지 방안을 서비스에 맞게 적절하게 조합해서 같이 사용하지 않나?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/system-design-interview#16]
pg. 178
보통은 데이터 날것을 log 테이블에 저장해 두고, 어느 정도 가공된(집계된) 데이터들을 또 따로 저장하여 그것을 사용하지 않나요?
책에서는 그냥 이런 방법들이 있구나 하고 알려주는 것일까요?

**Comment by ycheese** [comment]
그런 것 같아요.
회사에서 좀 더 중요하게 생각하는 게 무엇인지에 따라서 트레이드오프를 고려해서 선택하게 되지 않을까 싶습니다.
_앞으로는 이슈에 3가지 방안(178p) 써주시기 바랍니다._
