### ISSUE TITLE
[5장] 지표 수집 풀 모델 vs 푸시 모델 당신의 선택은?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#17]

**Comment by ycheese** [comment]
**손**
완전히 역할이 분리되는 게 좋다고 생각해서 푸시 모델
수집기 서버를 두는게 풀 모델

**스**
스님이 불러온 숙제


**주**
풀 모델
- 엔드포인트를 하나로 관리할 수 있는게 편리한 것 같고요.
- 안정 해시 링 -> 특정 지표가 특정한 서버에서만 처리됨이 보장되는게 좋아보여서 선택했습니다.

**Comment by behappyalltt** [comment]
푸시 모델
- 최근 역할 분담, 단일 역할에 대해 관심이 많아서 푸시 모델이 더 끌립니다
- 지표 전송 지연도 더 낮습니다
- 다만 데이터 신빙성을 위하여 인증 등을 강제할 필요가 있을 것 같습니다

**Comment by HYEMSTER** [comment]
**푸시 모델**을 선택하겠읍니다.
- 요즘 Event Driven Architecture가 트렌드인 것 같구요, 저도 단순한 아키텍처를 설계하기 위해서는 각 컴포넌트가 단순한 책임을 가지고 있는 게 좋다고 생각합니다.
- 언제 어떤 트래픽이 발생하게 될 지 모르는 상황에서 pull 모델은 비교적 비효율적인 것 같고, 지표 출처에서 트래픽이 발생하는 시점에 push하는 것이 더 효율적이지 않나 생각합니다.
- 트래픽이 몰리게 되는 상황에서도 수집기 컴포넌트만 스케일링하면 되기 때문에 관리 포인트도 적어서 좋은 것 같습니다.
