### ISSUE TITLE
[6장] 중복 데이터를 제거하기 위해 오프셋을 기록하는 방법을 사용할 때 오프셋을 기록하는 것에 문제가 생기면?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/system-design-interview#18]
조금 더 좋은 방법은 없을까?

215p.

**Comment by ycheese** [comment]
주) 그래서 분산 트랜잭션을 사용한다고 책에서 본 것 같아요.
손) 오프셋에 기록하는게 실패하면 다 롤백되는거에요.
스) 오프셋 기록 실패로 다 롤백하면 효율적이지 않은 것 같은데
손) 데이터 중복이 더 민감하기 때문에 이 방법이 맞는 것 같습니다.
