### ISSUE TITLE
[6장] 워터마크 크기를 정하는 기준

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#19]
✍🏻 212p
> 워터마크의 크기는 비즈니스 요구사항에 따라 달리 잡는다.
워터마크 구간이 길면 늦게 도착하는 이벤트도 포착할 수 있지만 시스템의 이벤트 처리 시간은 늘어난다.
워터마크가 짧으면 데이터 정확도는 떨어지지만 시스템의 응답 지연은 낮아진다.

워터마크 크기를 정할 때 기준 값으로 사용할만한 데이터는 어떤 것들이 있을까?
그리고 그 기준 값을 얻기 위해 어떤 방법을 시도해볼 수 있을까?

**Comment by ycheese** [comment]
주) 조정할 때 얼마나 많은 값이 조정되었는지? 를 모니터링할 수 있지 않을까요
손) 처리 시간을 보고 평균 값으로 한다?
스) 몰루

**Comment by behappyalltt** [comment]
이벤트 요청수와 이벤트 처리 시간을 보고 결정하면 좋지 않을까요?
이벤트 요청수가 많으면 워터마크 구간을 길게 처리하는 것이 좋을 것 같고,
이벤트 처리 시간(이벤트 처리 시간 평균?)을 측정하여 요청수와 함께 어느 정도의 성능을 원하는지에 따라 결정하면 될 것 같습니다.

**Comment by HYEMSTER** [comment]
지곰님께서 코멘트 달아주신 내용에 동의합니다.

from GPT...
> **이벤트 도착의 시간 분포**: 이벤트가 시스템에 도착하는 시간 간격을 분석하여 워터마크의 적절한 길이를 설정할 수 있습니다. 이벤트가 빈번하게 도착하면 짧은 워터마크가 효과적일 수 있으며, 이벤트가 드물게 도착하면 긴 워터마크가 필요할 수 있습니다. 이 데이터는 로그 분석이나 시간 시리즈 분석을 통해 얻을 수 있습니다.
**시스템 처리 능력**: 현재 시스템이 얼마나 많은 이벤트를 처리할 수 있는지를 평가합니다. 시스템의 처리량과 지연 시간을 측정하여 이를 워터마크 길이 조정의 기준으로 삼을 수 있습니다. 이 데이터는 벤치마킹 및 성능 모니터링 도구를 사용하여 얻을 수 있습니다.
**데이터의 중요도 및 정확도 요구 사항**: 다루는 데이터의 중요성과 필요한 정확도 수준에 따라 워터마크의 크기를 조정할 수 있습니다. 예를 들어, 높은 정확도가 필요한 경우 긴 워터마크가 적합할 수 있습니다. 이 기준은 비즈니스 요구 사항과 데이터 분석을 통해 결정됩니다.
**역사적 데이터와 예측 모델링**: 과거의 이벤트 처리 데이터를 분석하고, 미래의 데이터 흐름을 예측하여 워터마크 크기를 최적화할 수 있습니다. 예측 모델링은 머신 러닝 알고리즘을 사용하여 수행할 수 있습니다.
**시스템의 장애 내성 및 복구 시간**: 시스템이 장애 발생 시 얼마나 빨리 회복할 수 있는지를 고려하여 워터마크 크기를 결정할 수 있습니다. 장애 발생 시 데이터 손실을 최소화하고 시스템의 안정성을 유지하기 위해 긴 워터마크가 필요할 수 있습니다.
