### ISSUE TITLE
[6장] 워터마크 기법으로도 처리하지 못한 이벤트는 어떤 시각을 사용해서 집계해야 할까?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#20]
워터마크 기법으로 처리하지 못한 이벤트는 사소한 데이터 오류로 하루치 데이터 처리를 마감할 때 조정할 수 있다고 했다. (212p)
하지만 조정 파트(225p)에서는 이렇다 할 해답이 없어보인다.

시간 파트(210p)에서는 집계를 위해 `이벤트 시각`과 `처리 시각`이 사용될 수 있다고 했는데,
**워터마크 기법으로 처리하지 못한 이벤트**를 추후에 조정할 때는 **이벤트 시각과 처리 시각의 차이가 상당할 것**으로 예상된다.
이 둘 중 어느 시간으로 집계에 사용해야 할까?

**Comment by ycheese** [comment]
스) 집계에 사용하는 건 그래도 이벤트 시각이 좋지 않을까요?
손) 왜요?
스) 실제 처리 요청은 이벤트 시각이니까 그게 맞지 않을까요?
주) 저도 그렇게 생각해요.. 책에서도 처음에 이벤트 시각이 정확성 측면에서 더 맞다고 얘기하기도 했어서 다소 안정성이 처리 시각보다 떨어지겠지만 그래도 이 경우는 이벤트 시각이 더 맞아보입니다.
손) 몰루

**Comment by behappyalltt** [comment]
모든 것이 그렇듯이 상황에 따라 다르겠지만
제 생각은 실제 처리 요청이 진짜 발생한 이벤트 시각이니까 정확도를 위해서는 이벤트 시각을 사용하는 것이 좋을 것 같아요
대신 누락되는 이벤트는 어떻게 처리할 것인지 방안을 생각해야 할 것 같습니다

**Comment by HYEMSTER** [comment]
저 또한 저라면 이벤트 발생 시각을 기준으로 집계할 것 같습니다.
이벤트 시각과 처리 시각의 차이가 상당할 것이라면 더더욱 정확도 측면에서 이벤트 시각을 사용하는 게 좋아보입니다!
