### ISSUE TITLE
[7장] Auto Incremented 된 ID 값을 클라이언트에 노출하는 것

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#22]
235p의 예약 접수 API에 전달하는 파라미터를 보고 떠올랐는데요, 저희 회사에서 큰 논의 거리가 되었던 이슈이기도 합니다.

Auto Incremented된 ID를 클라이언트에 노출하는 것 괜찮을까요?
안괜찮다고 생각하는 이유는 클라이언트에서 값을 하나씩 올려가면서 크롤링을 하게 될 수도 있고, 해당 값을 통해 대략적인 서비스의 규모나 수치 등(예약이 얼마나 발생했는지, 등록된 매장 개수가 몇 개인지 등)을 사용자에게 노출할 수 있다는 우려때문입니다.

여러분들은 어떻게 생각하시나요?
만약 안괜찮다면 대안책은?

**Comment by behappyalltt** [comment]
손) auto_incremented 된 ID를 암호화 해서 보여주고 있음, 근데 코드가 많아 길어집니다
주) 근데 그 코드가 많아지면 한번에 처리가 가능하지 않을까요?
손) 오 그러면 좋겠다
스) 저희는 노출을 그냥 하긴 하는데 최대한 불필요하지 않은 경우에는 빼려고 합니다 습관적으로 모델에 담는 경우가 있는데 이런 경우를 줄이고 있습니다 안좋다고 생각은 하나 그 해결을 하지 못함
주) 괜찮은 것 같은 게 노출을 해서 문제가 되는 경우를 잘 모르겠음
스) 이커머스에서는 그럴 수도 있겠네요
