### ISSUE TITLE
[7장] 동시성 문제 해결해 본 경험 이야기하기

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#24]
redis(lettuce)를 통한 재고 관리
- named lock과 유사하게 계속 락을 시도하는 방식(spin lock)이라 redis에 부하 가능성이 있음
- redisson 방식(pub-sub)으로 하면 redis 부하는 감소할 수 있지만 구현이 복잡하고 별도 라이브러리를 사용해야 한다는 단점

**Comment by behappyalltt** [comment]
스) 자동취소가 되는 시간에 유저가 미션을 인증해서 동시성 이슈가 발생한 경우가 있는데요 비관적 락을 사용해서 동시성 이슈를 해결하였습니다
손) 잘 모르겠는데요 캐치테이블도 비슷하게 되어 있다고 생각했어요 예약 상세 페이지에 들어가는 시점에 홀딩 id, 예약 완료되는 시점에 홀딩 id를 저장함 근데 동시성 문제를 해결해 본 경험은 잘 모르겠어요 pk로 db로 알아서 막히게 하기?
주) 디비제약을 걸었네요? 포장하세요
손) try-catch로 로그 남기기 -> 따닥 이슈 해결
