### ISSUE TITLE
[8장] 메일에 첨부된 대용량 파일은 왜 다운로드 횟수를 제한할까요?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#25]
대용량 첨부파일은 **네이버 메일** 기준 `30일 보관 100회 다운로드 가능`이라고 합니다.
30일 보관의 이유는 저장용량의 최적화라고 쉽게 유추할 수 있는데요.
100회라는 다운로드 제한을 거는 이유는 무엇일까요?

**Comment by behappyalltt** [comment]
스) 다운로드 리소스를 줄이기 위해서 아닐까요?
손) 그쵸 리소스 많이 들 것 같아요
스) 네이버 클라우드를 사용하게 하려고 하는 것도 있대요
주) 그럼 지메일도 마찬가지겠다
손) 대박
