### ISSUE TITLE
[8장] 스팸 발송자인지 어떻게 구분해야 할까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/system-design-interview#26]
277 pg

외부 전송 담당 SMTP 작업 프로세스가 이메일의 스팸 및 바이러스 감염 여부를 확인한다고 하는데 이때 스팸 메일인지는 어떻게 확인해야 할까?
단순하게 제목 및 내용에 들어간 단어들을 체크하는 것만으로도 충분할까?

**Comment by behappyalltt** [comment]
주) 전송 가능성에 있는 게 국룰이 아닌가요?
손) 내부적으로 어떤 알고리즘을 쓰는지 궁금하네요
스) 결국에는 옛날에 어떤 파트였는지 기억이 안나지만 이런 필터링 관련 작업하는 거 있었는데 그때도 결론이 ai나 머신러닝을 사용해서 학습시켜라 그리고 알고리즘을 구축해라 였는데.. 비슷할 것 같기는 하네요
손) 메일 시스템은 ai 이전부터 필터링했는데.. 어떤 알고리즘인지 궁금하네요

**Comment by ycheese** [comment]
**1. 유명한 스팸 키워드 탐지 (광고, 할인, ...)**

**2. 헤더를 분석해서 `위조되었는지 확인`**
메일 인증 메커니즘(SPF, DKIM, DMARC) 으로 _이메일이 실제 해당 도메인에서 보낸 것인지 확인_ 가능하다고 함

**3. 블랙리스트 확인**

**4. ai 학습시키기**
 실현 가능성 👍🏻

**Comment by behappyalltt** [comment]
우리가 궁금했던 건 결국 ai 이전에 어떻게 스팸 메일을 필터링했냐 이건데 결국 단어와 규칙 기반 필터링이었던 것 같습니다
거기에 블랙리스트, 화이트리스트까지

이거 읽어보는 거 추천합니다!
https://brunch.co.kr/@8d1b089f514b4d5/53

**Comment by HYEMSTER** [comment]
텍스트 기반으로 필터링 + 헤더 분석을 통해 스팸 메일인지 분류하고, 특정 도메인에서 반복적으로 스팸 메일을 발생한 이력이 있는 경우 블랙리스트에 등록되는군요~
텍스트 기반 필터링 + 헤더 분석 프로세스는 점차 머신러닝을 통해 발전해가고 있구요~
그렇지만 필터링의 기반이 텍스트이기 때문에 100% 정확한 필터링은 힘들겠죠?
