### ISSUE TITLE
[8장] read/unread 테이블을 분리(비정규화)했을 때 페이징 처리

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#27]
> 284p
emails_by_folder 테이블을 두 테이블로 분할한다.
- read_emails: 읽은 상태의 모든 이메일을 보관하는 테이블
- unread_emails: 읽지 않은 모든 이메일을 보관하는 테이블

이렇게 비정규화했을 때 페이징 처리는 어떻게 구현하게 될까?

**Comment by behappyalltt** [comment]
손) **전체 테이블은 두개를 두고 비정규화된 테이블을 추가로 생성한다는 뜻**인가? 그러면 고려할 필요 없어져요
주) 그렇네요
스) 만약 따로라고 해도 join 하면 되는 거 아닌가요?
손) limit 만큼 가져오고 합쳐서 자르나요
