### ISSUE TITLE
[9장] N중 복제에서 N을 결정하는 기준과 고려해야 하는 사항은 무엇일까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/system-design-interview#28]
본 설계안에서는 3중 복제를 사용했다고 하는데 3이라는 숫자는 다른 설계안에서 다른 숫자가 될 수도 있다
N중 복제에서 N을 결정하는 기준과 고려해야 하는 사항은 무엇일까?

**Comment by HYEMSTER** [comment]
스) 가용성에 영향을 주지 않는 게 중요하기 때문에 데이터 중요도나 손실범위 고려
손) 가용성과 비용 사이의 트레이드오프
주) N이 1 이상일테니까 비용이 중요할 것 같다
