### ISSUE TITLE
[9장] 응답 지연보다 저장소 비용이 중요한 경우는 뭐가 있을까?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#29]
데이터 내구성 파트에서 다중화와 소거 코드를 비교하면서
- 다중화 : 응답 지연이 중요할 때 
- 소거코드 : 저장소 비용이 중요할 때
사용한다고 했다.

데이터 내구성을 위해 어느 정도 비용이 투자돼야 하니까 대부분의 경우에서 응답 지연을 우선하지 않을까? 저장소 비용이 더 중요한 경우는 뭐가 있을까?

**Comment by HYEMSTER** [comment]
소거코드를 사용하면 저장소 비용을 아낄 수 있으니까.. 회사에서 투자를 안해줄 때

**Comment by HYEMSTER** [comment]
주) 왜 앞서나가냐?
손) ㅗ
스) 데이터를 오래 보관하는 경우 비용이 중요하다
손) 다중화 vs 소거코드에서는 기간 고려 X 아닌가요?
주) 제가 생각했을 때도 현실적으로.. 회사에서 투자를 안해주는 그런 문제밖에는
손) 기술적보다 비즈니스 관점에서
스) 비즈니스 이슈?
손) ㅇㅇ
손) 비즈니스 관점에서 회사에서 중요하게 생각하지 않는 사업이라던가.. 트래픽이 적어서 소거코드로 충분하다던가 그런 이유이지 않을까요
주) 동의합니다
스) 동의합니다
