### ISSUE TITLE
[9장] 객체 저장소에서 강한 일관성(String Consistency)을 제공해야 할까?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#30]
313p. (데이터 저장 흐름)
> 주 데이터 노드는 데이터를 자기 노드에 지역적으로 저장하는 한편, 두 개의 부 데이터 노드에 다중화한다. 
주 데이터 노드는 데이터를 **모든 부 데이터 노드에 성공적으로 다중화하고 나면** 데이터 라우팅 서비스에 응답을 보낸다.

위에서 설명하는 내용이 강한 일관성을 의미하는데, 객체 저장소에서 강한 일관성이 보장되어야 할까?
결과적 일관성(Eventually Consistency)만 보장된다면 문제가 될까?

**Comment by HYEMSTER** [comment]
주) 데이터 노드 수가 적을 수록 문제가 될 확률이 높을 것 같다.
손) **만약 복제가 완료되지 않은 노드에서 객체를 찾을 때 어떻게 우회할 수 있는**지 ? ?
스) 에취 에취!
손) 그리고 또 강한 일관성을 적용하게 되면 노드 수가 늘어날수록
주) 지연이 높아질 것 같단 말이죠
스) 404가 맞나? 모르겠다

**Comment by ycheese** [comment]
손님이 말하는 `만약 복제가 완료되지 않은 노드에서 객체를 찾을 때`에 대한 전략을 멋진 말로 `읽기 일관성 전략`이라고 하는 것 같아요.
시도해볼만한 전략들은
1. 복제가 완료될 때까지 재시도하기
2. 쓰기 후 특정 시간동안 주 데이터 노드에서만 읽기
3. 리드 쿼럼 : `쿼럼`(읽기 요청을 처리하는 데 필요한 최소한의 복제된 노드 수) 값을 미리 설정해놓고 리드 쿼럼 크기만큼 복제된 경우에 복제된 노드에서 데이터 읽기

이렇게 3가지가 있는데 **리드 쿼럼** 내용이 재밌어서 더 찾아봤어요.
**읽기 요청 시 리드 쿼럼 크기만큼 복제되지 않은 경우**에 처리가 또 문제가 될 것 같은데
- 응답 거부
- 타임아웃만큼 대기
- 다른 전략 쓰기

일반적으로 이렇게 쓴다고 합니다.
그럼 리드 쿼럼 전략을 취하고 실패 시 1, 2번도 같이 혼용해서 쓸 수 있지 않을까요?

**Comment by HYEMSTER** [comment]
은행 시스템과 같이 정확한 읽기 일관성이 보장되어야 하는 경우가 아니라면, 
낮은 지연시간이 더 중요하다고 생각해서 강한 일관성보다는 결과적 일관성을 채택할 것 같습니다.

결과적 일관성을 보장하되 레플리카 복제 지연을 최대한 우회하는 방법으로 
치즈님께서 설명해주신 방안과 더불어 추가로 어플리케이션 레벨에서 아래와 같은 방법을 생각해볼 수 있을 것 같아요.
- 저장 후 바로 읽을 때(ex. 블로그처럼 게시글 등록 후 바로 나의 게시글 조회 요청)는 요청한 객체를 클라이언트가 가지고 있다가 보여주기
- 자신이 쓰기-조회를 연달아서 수행하는 플로우의 경우 무조건 주 노드에서만 읽도록 하기 (치즈의 2번 방안과 비슷)

**Comment by behappyalltt** [comment]
저도 치즈님이 언급한 리드 쿼럼 전략이 좋을 것 같다고 생각합니다
확장성보다는 일관성이 더 중요하고, 데이터 핫스팟이 심할 것 같지는 않아서 **수치적 리드 쿼럼** 전략을 사용하면 좋을 것 같습니다

- 수치적 읽기 쿼럼
  - 특정 수의 노드에서 동일한 값을 반환해야 하는 전략
- 비율 기반 읽기 쿼럼
  - 읽는 노드의 비율이 특정 임계값을 초과해야 하는 전략
- 기반 읽기 쿼럼
  - 특정 노드에서 읽어야 하는 전략
 
참고: https://medium.com/@pnkcomm2u/quorum-consistency-vs-availability-7814451d06de
