### ISSUE TITLE
[10장] API gateway와 AWS Lambda로 게임 서버에서만 호출할 수 있는 내부 API 구성 방법

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#31]
어떻게 게임 서버 내부에서만 호출할 수 있게 할 것인가?

**Comment by HYEMSTER** [comment]
손) 인증 헤더
스) 권한 설정같은거?
**주) 람다 함수를 구성하고 IAM 권한 설정하고, 엔드포인트 설정하고 그런 흐름을 정리해보자.**
스) 이게 답 아닌가요?
주) 시비 ㄴㄴ
손)
- 필요한 API 명세를 작성하고, 엔드포인트를 API Gateway에 등록한다.
- 내부 API이기 때문에 인증 헤더를 하나 두고 내부 요청인지 체크한다. (IAM, Secret Key 등 활용)
- 람다함수 작성해서 엔드포인트와 연결한다.
스) **API 키**를 발급한다? AWS에 그런 거 있지 않나?
손) 시크릿키?
주) 서버에서 사용하는 키를 applicaton config로 관리하지 않고 AWS로 위임해서 관리하는 거구나
손) 전 람다 써봤어요
주) 람다가 AWS에서 어플리케이션 하나로 다뤄지는건가요?
손) 어떤 이벤트가 발생했을 때 실행되는 로직 하나 (함수 하나로 구성되기 때문에)
주) 어떤 이벤트가 발생했을 때 기준을 어떻게 정하나?
손) CloudFront에다가 Lambda@Edge로 람다함수를 연결시켜서 사용했었는데, 이 때는 선택할 수 있는 옵션이 원본 저장소에 객체가 들어올 때/삭제될 때, CloudFront에 캐싱될때/삭제될때 등등
주) 이벤트리스너처럼 람다가 이벤트 감지?
손) 맞습니다~
스) GCP CloudFunction 써봤다. 람다랑 비슷하다.
