### ISSUE TITLE
[10장] 만약 본인이라면 Redis와 NoSQL 중에 어떤 것을 선택할 것인가?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/system-design-interview#32]

**Comment by HYEMSTER** [comment]
스) NoSQL을 써보고싶다. 이유는 써보고싶기 때문이다. 예산이 되면 쓰게 해주세요.
손) 다이나모에서 파티션키랑 세컨더리 인덱스로 정렬을 쉽고 빠르게 하는 방법을 소개해줬는데, 이게 있어서 충분히 다이나모로 대체 가능할 것 같다. 그 외 몽고디비나.. 이런 건 잘 모르겠다. 근데 ZSet이 너무 강력한 것 같다.
주) 멋집니다. 저는 같은 이유로 다른 선택을 했는데 NoSQL 안써봤기 때문에 Redis를 쓰겠다.
손) Redis 영속성 문제만 잘 해결하면 전 Redis요. 훨씬 빠르고, 이 설계안에서 중요하게 생각하는 순위표 구현에 ZSet만한 자료구조가 있을까요?
