### ISSUE TITLE
[11장] 결제 상태 추적을 위해 어떤 데이터베이스에 결제 상태를 저장하는게 좋을까?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#34]
> 390p - 결제 상태 추적
> (중략) ... 결제 상태는 **데이터 추가만 가능한** 데이터베이스 테이블에 보관한다.

개략적 설계에서 트랜잭션 처리를 위해 `RDB`를 사용하기로 했다.
일반적으로 데이터 추가만 가능한 저장소는 `NoSQL`이 떠오르는데 ??
책의 내용을 신경쓰지 않고 **상태 추적을 위한 결제 상태를 저장하는 데이터베이스는 뭐가 좋을지** 이야기해봅시다.

**Comment by behappyalltt** [comment]
책에서는 다른 로직에 적용할 트랜잭션 처리를 위해 RDB를 같이 사용했는데
진짜 딱 상태 추적을 위한 결제 상태를 저장하는 것만 생각한다면 저도 NoSQL이 더 좋아보입니다
정보를 많이 저장할 것 같지도 않아서 데이터 모델링에 크게 신경 쓸 필요도 없고, 성능도 좋은 NoSQL이 더 좋지 않을까요?

**Comment by ycheese** [comment]
- 손: 상태 데이터만 추가한다는게 이벤트 스트림처럼 데이터를 쌓겠다는 그런 뜻인거겠죠?
- 주: 비슷하지 않을까요?
- 스: 전 댓글 달았어요
- 주: 앞서나가시네요 .. 👍🏻
- 손: 트랜잭션 처리는 하지만 실패니까 noSQL 트랜잭션 처리가 되나요? 안되지 않나요?
- 스: 안돼요
- 손: 어 근데 레디스는 트랜잭션 되는걸로 아는데 레디스는 스프링에서 같은 트랜잭션을 적용할 수 있더라고요 하튼 전 nosql이 적당하다고 생각합니다.
- 스: 레디스 트랜잭션은 ACID를 만족하지 않는다고 하던데
- 손: 그럼 그게 트랜잭션인가요?
- 주: 덧붙이자면 mysql이랑 postgresql 비교할때 post가 ACID를 더 충족한다 이렇게 얘기하고는 하는데 그런 의미에서 만족하지 않는다는게 아닐까요
- 스: 완벽하게 보장하지 않는다고 했어
- https://velog.io/@xogml951/Redis-%EB%8F%99%EC%8B%9C%EC%84%B1-%EB%AC%B8%EC%A0%9C-%EB%B0%A9%EC%A7%80Transaction-Lua-Scripting
