### ISSUE TITLE
[11장] 조정 단계에서 불일치 문제를 해결하는데 만약 해결하지 못한 경우에는 어떻게 해야 하나?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/system-design-interview#35]
조정 단계에서 불일치 문제를 해결하는데 **분류할 수 없는 유형의 문제**로 해결하지 못한 경우에는 어떻게 해야 하나?
금액이 일치하지 않을 수도 있는데 이럴 때는 어떻게 해야 하는지?
고객한테 전화해서 사죄 후 추후에 배상을 해주면 되는 건가?

**Comment by ycheese** [comment]
- 주: 제 생각에는 싹싹 빌어야 한다고 생각해요.
- 손: 운영으로 풀고
- 스: 방법이 그거밖에 없을까요?
- 손: 사람이 고치고 로직을 만들어야 겠죠
- 스: 그전엔 고객에게 양해를 구하는 방법밖에 없나요
- 주: 싹싹 구해야 됩니다.
- 손: 일단 싹싹 빌고 어드민이라도 만들 수 있게끔. 
- 주: 두번 다시 안 일어나게...
- 손: 아니면 일어나도 빨리 처리하게 !!
