### ISSUE TITLE
[11장] 재시도 매커니즘에서 네트워크 문제가 단시간 내에 해결될 지 아닐지 판단할 수 있는 근거로 어떤게 있을까?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#36]
제곧내

**Comment by HYEMSTER** [comment]
+ 다음주 수요일 스킵하고 일요일에 하는 거 어떨지?
1) 12장 1~2장 분량이 꽤 길다
2) 손님의 여행 이슈

**Comment by ycheese** [comment]
- 주: 노션같은거 자주 오류나잖아요.? 그런것처럼 일단 들어가봐서 나만 지금 좀 느린거다 나만 지금 잘안되는거다 -> 빨리 해결될만함 / 트위터에 노션 지금 다 안된대 -> 위험
- 스: 시스템 문제인지 먼저 확인을 하고? 또 얼마나 문제가 지속됐는지
- 손: 그럼 계속해서 찔러보는수밖에 없겠네요
