### ISSUE TITLE
[12장] 데중설 책 추천합니다.

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#37]
12장 개략적 설계안에 나오는 분산 트랜잭션~이벤트 소싱 내용 **데이터 중심 애플리케이션 설계**라는 책에 다 나오는데요,
그 책에서 자세히 설명해주고 있어서 이 책 한 번씩 읽어보길 추천합니다 ~

저는 작년에 이 책으로 회사에서 스터디 했었는데.. 반도 이해 못했어서 다시 한 번 읽어보려구여
담에 데중설 책으로 우리끼리 스터디해도 좋구요
그냥 생각나서 적어봤심더

**Comment by ycheese** [comment]
다음 스터디 좋아요
