### ISSUE TITLE
[12장] 코레오그라피 vs 오케스트레이션

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#38]
코레오그라피 패턴과 오케스트레이션 패턴의 장단점과, 일반적인 커머스(주문&결제) 서비스에서는 어떤 패턴이 더 적절할 지 논의해보고 싶습니다.

> 419p
> - **분산 조율(Choreography)**: 마이크로서비스 아키텍처에서 사가 분산 트랜잭션에 관련된 모든 서비스가 다른 서비스의 이벤트를 구독하여 작업을 수행하는 방식. 완전히 탈 중앙화된 조율 방식이다.
> - **중앙 집중형 조율(Orchestration)**: 하나의 조정자가 모든 서비스가 올바른 순서로 작업을 실행하도록 조율한다.

코레오그라피는 병렬 실행이 가능하지만 롤백이 까다로울 것 같고,
오케스트레이션은 롤백이 비교적 간단한 반면 장애 전파와 조정자가 SPOF가 될 수 있을 것 같습니다.

**Comment by ycheese** [comment]
서비스 간 작업 흐름 조율을 위해 오케스트레이션 패턴이 적절해보입니다.
SPOF 문제가 걱정된다면 백업 조정자를 구성하는 건 어떨까요?
모니터링도 중요할 것 같아요

**Comment by behappyalltt** [comment]
커머스 서비스에서는 데이터 일관성이 중요하기 때문에 오류가 생겼을 때 롤백에 용이한 오케스트레이션 패턴이 더 적절해 보입니다
SPOF 문제는 클러스터링이나 로드 밸런싱처럼 트래픽과 서버를 분산하는 방법을 사용하여 예방하는 것이 좋을 것 같습니다
또한 치즈님이 이야기한 것처럼 모니터링도 중요할 것 같습니다

**Comment by HYEMSTER** [comment]
마음에 쏙 듭니다.
사실 저희도 오케스트레이션 패턴을 거의 대부분 사용해요~
