### ISSUE TITLE
[12장] 스냅샷을 사용한다면 주기는 어떻게 가져가는게 좋을까요?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#39]
1. 주기가 길면
- 이벤트 이력을 재생해서 만드는 케이스가 늘어나고
- 그만큼 스냅샷을 안 쓸 것 같고
2. 주기가 짧으면
- 저장소 용량을 많이 차지하고
- 안 쓰이는 스냅샷을 구분하기 어려울 것 같아요

어떻게 생각하나요?

**Comment by behappyalltt** [comment]
전자 지갑 서비스의 경우에는 주기를 짧게 가져가면서 백업을 해두고, 백업할 때 백업 유지 기간을 잘 설정하는 방법이 좋을 것 같습니다
일반적으로 거래 빈도가 높을 것 같기도 하고, 또한 돈과 관련된 작업이기 때문에 데이터 손실 위험을 최소화하는 것이 좋을 것 같습니다

**Comment by HYEMSTER** [comment]
손) 트레이드오프네요
손) 짧게라면 하루정도? 짧게가 얼마나 짧게인가요?
스) 그건 고민입니다
손) 콜드 저장소? 그런 거 사용하는 게 좋을 것 같고 스님의 의견에 동의합니다 (민감한 정보이므로 짧게 저장해서 손실을 최소화한다.)
스) 비용은 감당해야 한다.
주) 마음에 쏙
