### ISSUE TITLE
[2장] Redis Pub/Sub에서 메시지 발행 또는 수신에 실패할 경우 이를 감지하거나 재시도 할 수 있는 메커니즘

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#4]
메시지 발행 또는 수신에 실패할 경우 우리가 감지할 수 있는 방법 또는 Redis에서 제공하는 매커니즘이 있을까요?

**Comment by HYEMSTER** [comment]
온라인 사용자인데 30초마다 메시지 발행을 안했다면 누락으로 간주한다.

**Comment by ycheese** [comment]
메시지 처리 후 특정 값을 리턴하도록 해서(ACK) 그 값이 리턴되지 않으면 메시지 처리 실패로 간주할 수 있을 것 같다.
재시도 또한 위 방법으로 메시지 처리 실패가 감지되면 정해진 재시도 횟수만큼 일정 간격을 두고 재시도하면 될 것 같은데, **책에서 나온 설계안에 따르면 30초마다 위치 정보를 갱신하는데 재시도하는게 크게 의미가 있을지 ?**

재시도 로직을 넣게 된다면 아주 특별한 상황 (예를 들면 아래와 같은)
```
- 온라인 친구 모두의 위치 정보를 못 받아왔다든지
- 내 위치 갱신 요청을 보냈는데 연속 2회 이상 처리가 안됐다든지
```
에 대한 케이스를 정의해서 재시도로 인한 서버 부하를 만들지 않도록 해야겠다.

**Comment by behappyalltt** [comment]
저도 메시지 처리 후 특정 값을 리턴하도록 해서 그 값이 리턴되지 않으면 메시지 처리 실패로 간주하는 것이 가장 좋을 것 같습니다.
오히려 재시도를 어떻게 처리할지가 더 중요할 것 같아요.
채은님 말처럼 30초마다 위치 정보를 갱신하기 때문에 바로 재시도 하는 것은 의미가 없을 것 같고, 어떤 조건에 재시도를 할지 고민해 봐야 할 듯 합니다.

채은님 의견에 이어서 제가 생각하는 로직은
`마지막 갱신 시간에서 n분 이상 처리를 하지 못 할 때(온라인, 오프라인 확인이 필요하기는 함)`
입니다.

**Comment by HYEMSTER** [comment]
Redis Pub/Sub 자체적으로 메시지 발행이나 수신에 대한 실패 감지는 지원하지 않는 것 같다.
- Pub/Sub 메커니즘은 기본적으로 Publisher와 Subscriber 간의 느슨한 결합을 지원한다.
- 메시지가 전송된 후 해당 메시지는 바로 삭제되어 어디에도 저장되지 않는다.
- 메시지 신뢰성을 보장하지 않는다.

**그럼 수신 실패를 감지할 수 있을까? 어떻게 최신성을 보장해야 할까?**
- Publisher 입장에서는 메시지를 발행하기만 하면 역할이 끝나고, Subscriber 입장에서도 메시지가 실제로 수신되었는지 감지할 방법은 없어보인다.
- 대신 온라인일 때 주기적으로 위치를 갱신하면서 최신성을 최대한 보장하도록 하는 게 최선의 방법일 것 같다.
- Redis 자체의 CPU나 메모리 이슈가 아니면 크게 걱정하지 않아도 될 상황인 것 같기도 하다.

그치만 근본적으로 메시지 누락에 민감한 서비스라면 Redis Pub/Sub 말고 메시지의 지속성이 보장되는 다른 이벤트 스트림을 사용하는 것이 맞는 것 같다! (Kafka, Redis List, Redis Stream 등등..)
