### ISSUE TITLE
[13장] 코로케이션을 효과적으로 감독할 수 있는 방법은 무엇일까?

### ISSUE THREAD

**Issue by behappyalltt** [thisandthat-lab/system-design-interview#41]
pg. 486

코로케레이션은 악용한다면 공정성, 정보 불균형, 시장 조작 가능성 등과 같은 이슈들이 있을 것 같은데
이를 효과적으로 감독할 수 있는 방법은 무엇일까요?
조금 찾아봤을 때 아직 규제나 감독이 약한 것 같음

1. 시장 데이터를 분석하여 코로케이션과 관련된 비정상적인 거래 패턴을 파악해서 조사하기
2. 코로케이션 서비스 제공자의 사업 운영 방식 규제하기
3. 증권 거래소 사업자들의 도움이 필요할 것 같음
4. 해외에서 어떻게 하는지 조언을 구하는 것도 좋을 듯

**Comment by ycheese** [comment]
- 스: 공정성 이슈가 없다고 하는데 애매하지 않나요?
- 손: 어뷰징할 수 있겠죠 아이피 패턴을 보고 판단한다. 그래서 뭔가 우리가 사전에 협의된 대역이 아니면 차단한다.
- 스: 내가 의도한 거랑 다른 답변인 것 같아 증권거래소 입장이 아니라 밖에서 볼 때 뭔가 그런 느낌
- 주: 기관에서 감독해야 한다는 말?
- 스: 코로케이션을 증권거래소 자체가 악용할 것 같아서
- 손: 우리 시스템에서 부적절한 사용자를 쳐내야 우리 시스템의 평판이 올라가고 그런거 아닌가
- 스: 그건 다른 개념. 시장가를 조작하고 이런게 가능할 것 같아서 실제로 국가에서도 이걸 모니터링 하고 있다고 했거든
- 주: 법으로 심판한다...
- 손: 그게 맞는 것 같아요 거래처 입장에서는 할 수 있는게 없죠
