### ISSUE TITLE
[13장] 시장 데이터의 공정한 배포

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#43]
> 485~486p
안정적 UDP를 사용하는 멀티캐스트는 한 번에 많은 참가자에게 업데이트를 브로드캐스트 하기 좋은 솔루션이다.
구독자가 연결하는 순서로 데이터를 주는 대신, 무작위 순서로 주는 방법도 있다.
...
같은 멀티캐스트 그룹에 속한 수신자는 이론적으로 동시에 데이터를 수신한다.
그러나 UDP는 신뢰성이 낮은 프로토콜이며 그 데이터그램은 모든 수신자에게 도달하지 못할 수도 있다.

UDP의 신뢰성이 보장되지 않아 모든 수신자가 동시에 데이터를 수신하는 것이 보장되지 못한다면,
무작위 구독자를 선정하여 데이터를 수신할 수 있도록 구현하는 게 좋은 방법 아닐까?

그럼에도 불구하고 보편적으로 멀티캐스트를 사용하는 이유는 무엇일까?

**Comment by ycheese** [comment]
- 주: 그래도 멀티캐스트를 사용하는 이유는 무작위 구독자 선정 -> 무작위 뽑는 과정이 있어야 하는데 UDP는 그런 과정이 없고 신뢰성이 낮지만 빠르다고 하잖아요. 지연 시간 측면에서 효율적이라서 그런게 아닐가.
- 스: 동의합니다. 코막혀..
