### ISSUE TITLE
[2장] 본 설계안에서는 배제한 팔로어 기능을 추가하고 싶다면 어떻게 해야 할까요?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#5]

**Comment by HYEMSTER** [comment]
- 내가 팔로잉하는 시점에 채널이 구독되도록 한다.
- 인스타그램처럼 상대방의 팔로우 요청을 내가 선택해서 받을 수 있도록 구현하면 좋겠다.

**Comment by behappyalltt** [comment]
- 친구 관계가 양방향만이 아닌 단방향도 가능하게 될 것
- 팔로워를 받고, 안받고에 따라(비계 팔로워 받아주고, 나는 맞팔하지 않는 것처럼) 나의 위치 정보 전송 허가 여부를 결정하면 될 듯
- 친구 관계 데이터 DB 변경
  - 맞팔 여부
- 팔로워만 나의 채널을 구독하게 하고 나는 그 팔로워의 채널을 구독하지 않도록만 수정하면 될 것 같다
- 생각보다 그렇게 복잡하지는 않을 듯
