### ISSUE TITLE
[2장] 클라우드 로드밸런서는 어떻게 유상태 서버 클러스터의 규모 확장을 지원할까요?

### ISSUE THREAD

**Issue by HYEMSTER** [thisandthat-lab/system-design-interview#6]

**Comment by HYEMSTER** [comment]
ex) 웹소켓
- 모든 소켓이 draining 상태가 될 때까지 기다렸다가 모든 연결 해제가 완료되면 그 때 서버를 종료한다던지.. 이런 걸 내부적으로 알아서 모니터링 할 것 같다.

ex) 웹서버, 디비서버
- 서버 삭제 요청 → 더 이상 새로운 연결을 맺지 않음 → 기존에 연결된 모든 연결이 종료될때까지 기다림 → 완료되면 알아서 삭제됨 이렇게 동작할 것 같다.

**Comment by ycheese** [comment]
클라우드 로드밸런서가 일반 로드밸런서보다 더 나은 점에 초점을 두면 `트래픽 증가에 자동 대응할 수 있다`는게 가장 큰 특징인데 이 특징은 유상태 서버 클러스터의 규모 확장과는 크게 관계가 없어보인다.
결과적으로는 책에 나온 내용 `로드밸런서가 인식하는 노드 상태를 연결 종료 중(draining)으로 변경하면 트래픽이 전달되지 않음`이 전부인듯하다. 더 깊게 들어가면 **로드밸런서의 health check** 관련된 내용인 것 같은데 더 찾아봐야 할듯 (근데 일반 로드밸런서에도 health check가 있을텐데...)

클라우드 로드밸런서만의 특별한 장점!!이 유상태 서버 클러스터의 규모 확장을 쉽게 해준다는 생각으로 주제를 냈던건데 접근이 잘못되었던 것 같다는 생각이 드네요. 🥹

**Comment by behappyalltt** [comment]
서버를 축소할 때: 노드 상태가 연결 종료 중일 때는 해당 노드로 트래픽을 전달하지 않고, 새로운 노드로 전달함
서버를 확장할 때: 로드밸런서가 알아서 새로운 서버에 분배하지 않나?

**Comment by HYEMSTER** [comment]
저도 책을 다시 읽어봤는데 책에서 설명한 내용이 전부인 것 같아요

> 사람: 노드를 제거한다.
서버 노드: 자신의 상태를 'draining'으로 변경하고, 시간이 흘러 모든 연결이 종료되면 그 때 제거된다.
LB: 'draining' 상태의 노드로는 새로운 요청을 보내지 않는다.

이 일련의 과정을 클라우드에서 알아서 잘 처리하고 있으니 개발자가 신경쓰지 않아도 된다?
이 정도로 이해하면 될까요🫠
