### ISSUE TITLE
[3장] 경로 계획 서비스가 응답을 만들기 위해 여러 서비스를 호출하고 매쉬업해야 한다. 서버 작업량과 네트워크 타임 측면에서 어떻게 성능을 개선해 볼 수 있을까?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#7]
병렬로 수행할 수 있는 작업이 아니어서 A → B → C 이런식으로 동작하는 것 같아서 레이턴시가 길어질 수 있겠다.

**Comment by ycheese** [comment]
- 각 서비스를 호출한 결과에 대해 최대한 캐시한다. 그러나 우리 설계안에서는 캐싱할만한 게 최단경로 말고는 없어보인다.
- 캐싱을 사용하더라도 실시간으로 가져와야 하는 데이터가 더 많아보인다.

**Comment by ycheese** [comment]
빠른 응답 속도를 위해 데이터를 압축해서 전송할 수 없을까? 압축을 푸는 비용이 더 많이 들까...?

**Comment by HYEMSTER** [comment]
**데이터를 압축해서 전송한다.**
- 네트워크에서의 병목은 언제 발생할 지도 잘 모르고 해결할 수 없는 부분이니까, 최대한 데이터를 압축해서 전송한다.
- 압축된 데이터를 해제하는 것은 서버의 몫이므로 우리가 컨트롤할 수 있는 영역일 것 같다.

**데이터를 캐싱한다.**
- 1초, 3초 등등... 아주 짧게라도 데이터를 캐싱해두는 정도는 괜찮지 않을까? (이 정도는 허용 범위 아니려나..? 아님말고..)
- 개략적 추정에서 나온 평균 QPS가 20만 정도라고 했으니까 성능이 확실히 개선될 것 같기는 하다..

**Comment by behappyalltt** [comment]
저도 캐싱이 가장 이상적인 방안이라고 생각합니다.
할 수 있는 데이터는 최대한 캐싱하여 짧게라도 사용하는 것이 좋을 것 같고,
돈이 많다면 서버를 이곳저곳에 여러 개를 두어 응답 시간을 최소화 해도 좋을 것 같습니다.
그리고 데이터 압축을 활용할 거면 압축 및 해제 알고리즘을 잘 선택해야 할 것 같습니다.
알고리즘에 따라 시간 차이가 많이 난다고 하네요.
