### ISSUE TITLE
[3장] 사용자 위치 데이터가 지도 데이터 개선(신규/폐쇄 도로 확인)에 쓰인다고 했다. 어떤 기준으로 신규/폐쇄 도로인지를 확인할 수 있을까?

### ISSUE THREAD

**Issue by ycheese** [thisandthat-lab/system-design-interview#9]
사용자 위치 데이터가 계속 변하니까 추적이 필요할 듯 하다.
특정 도로를 계속 추적해야 한다거나, 특정 사용자를 계속 추적해야 한다거나? -> **비효율적이라고 생각**

**Comment by ycheese** [comment]
- 사용자 위치 데이터만으로는 추측만 가능하고 100% 신뢰할 수 없다.
- 경로 추천 시간과 실제 사용자가 걸린 시간을 비교해서 개선한다.

**Comment by ycheese** [comment]
사용자 위치 데이터 변경시마다 `사용자 id`와 `위치 정보 데이터`를 따로 저장한 후
부하가 가장 적을 시간에 저장한 위치 정보를 하나씩 꺼내서

```
위치 정보가 도로임 && 사용자 접근 흔적 있음 == 정상(패스)
위치 정보가 도로임 && 사용자 접근 흔적 없음 == 모니터링 대상
위치 정보가 도로가 아님 && 사용자 접근 흔적 있음 == 모니터링 대상
```

어떤 위치가 n일 연속 모니터링 대상일 경우 신규/폐쇄 도로다. 라고 감지 가능하지 않을까
지난 번 토론때 보다는 덜 비효율적이지만 여전히 비효율적으로 보인다 ...

**Comment by HYEMSTER** [comment]
**신규 도로 감지**
- 지도 상에서 '도로'가 아니지만 사용자의 유입이 어느 순간부터 지속되면 신규라고 판단한다?

**폐쇄 도로 감지**
- 지도 상에서 '도로'이지만 사용자의 유입이 어느 순간부터 없다면 폐쇄라고 판단한다?

저도 주님의 마지막 댓글과 비슷하게 생각했는데 대신 전 배치 job이 아니라 모든 실시간으로 받는 데이터를 축적해서 판단한다라고 생각했어요.
그치만 100% 시스템이 처리할 수는 없고, 모니터링된 데이터를 바탕으로 인간이 직접 확인하러 나가는 작업이 필요하지 않을까요?

**Comment by behappyalltt** [comment]
주님, 손님이 말한 거에 다른 데이터도 같이 보면 좋을 것 같아요.
찾아 보니까 주행 속도도 좋은 참고 데이터가 될 것 같아요.
`새로운 도로는 일반적으로 높은 주행 속도를 나타내며, 반대로 폐쇄된 도로는 낮은 주행 속도를 나타낸다`고 하니 주행 속도를 저장해서 모니터링에 활용하면 좋을 듯 합니다.

그리고 저도 데이터만으로는 확실하게 판단할 수 없을 것 같다고 생각했어요.
근데 직접 확인하는 것이 현실적으로 가능할까 싶기도 하면서, 이런 직업이 있을 것 같다는 생각이 들기도 하네요.
사용자에게 제보를 받아도 좋을 것 같네요.
효율적인 경로였는지 피드백을 받으면서 같이 받으면 좋을 것 같아요. 이것도 직접 확인하는 과정이 필요하겠지만요.
